# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    color:#000;\n"
"    border:none;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color:#eeeee4;\n"
"}\n"
"#profileacc,#sidenav{\n"
"    background-color:#1e81b0;\n"
"}\n"
"QLineEdit{\n"
"    background:transparent;\n"
"}\n"
"QPushButton{\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"#searchFrame{\n"
"    border-radius:10px;\n"
"    border:2px solid #1e81b0;\n"
"}\n"
"#appHeadear{\n"
"    color:#1e81b0\n"
"}\n"
"#card1, #card2, #card3, #card4, #frame_6{\n"
"    background-color:#cbe4e8;\n"
"    border-radius:10px;\n"
"}\n"
"#equipment{\n"
"    border-radius:10px;\n"
"    border:2px solid #1e81b0;\n"
"}\n"
"\n"
"#borrower{\n"
"    border-radius:10px;\n"
"    border:2px solid #1e81b0;\n"
"}\n"
"\n"
"#time{\n"
"    border-radius:10px;\n"
"    border:2px solid #1e81b0;\n"
"}\n"
"\n"
"#date{\n"
"    border-radius:10px;\n"
"    border:2px solid #1e81b0;\n"
"}\n"
"\n"
"#viewmoreBtn{\n"
"    border-radius:5px;\n"
"    border:2px solid #1e81b0;\n"
"    background-color:#cbe4e8;\n"
"}\n"
"\n"
"#home{\n"
"    background-color:#eeeee4;\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border-top-left-radius: 20px;\n"
"}\n"
"\n"
"#addeq{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"\n"
"#transactlist{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"\n"
"#deleq{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"#equip{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"\n"
"#borrower_1{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"\n"
"#myprofile{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"\n"
"#logout{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"\n"
"#editborrower{\n"
"    padding:5px;\n"
"    text-align: left;\n"
"    border:none\n"
"}\n"
"\n"
"\n"
"#home{\n"
"    color:#1e81b0;\n"
"    border:none\n"
"}\n"
"\n"
"#transactlist, #borrower_1, #equip, #logout, #myprofile, #label{\n"
"    color:#ffffff;\n"
"    border:none\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu.setGeometry(QtCore.QRect(0, 0, 231, 601))
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sidenav = QtWidgets.QFrame(self.leftMenu)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.sidenav.setFont(font)
        self.sidenav.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidenav.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidenav.setObjectName("sidenav")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sidenav)
        self.verticalLayout_7.setContentsMargins(-1, -1, 0, 262)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.home = QtWidgets.QPushButton(self.sidenav)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.home.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blueIcons/icons/blueIcons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon)
        self.home.setIconSize(QtCore.QSize(20, 20))
        self.home.setAutoDefault(True)
        self.home.setFlat(False)
        self.home.setObjectName("home")
        self.verticalLayout_7.addWidget(self.home)
        self.equip = QtWidgets.QPushButton(self.sidenav)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.equip.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/whiteIcons/icons/whiteIcons/hard-drive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.equip.setIcon(icon1)
        self.equip.setIconSize(QtCore.QSize(20, 20))
        self.equip.setAutoDefault(True)
        self.equip.setFlat(False)
        self.equip.setObjectName("equip")
        self.verticalLayout_7.addWidget(self.equip)
        self.borrower_1 = QtWidgets.QPushButton(self.sidenav)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.borrower_1.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/whiteIcons/icons/whiteIcons/users.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.borrower_1.setIcon(icon2)
        self.borrower_1.setIconSize(QtCore.QSize(20, 20))
        self.borrower_1.setAutoDefault(True)
        self.borrower_1.setFlat(False)
        self.borrower_1.setObjectName("borrower_1")
        self.verticalLayout_7.addWidget(self.borrower_1)
        self.transactlist = QtWidgets.QPushButton(self.sidenav)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.transactlist.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/whiteIcons/icons/whiteIcons/list.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.transactlist.setIcon(icon3)
        self.transactlist.setIconSize(QtCore.QSize(20, 20))
        self.transactlist.setAutoDefault(True)
        self.transactlist.setFlat(False)
        self.transactlist.setObjectName("transactlist")
        self.verticalLayout_7.addWidget(self.transactlist)
        self.verticalLayout_6.addWidget(self.sidenav, 0, QtCore.Qt.AlignTop)
        self.profileacc = QtWidgets.QFrame(self.leftMenu)
        self.profileacc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profileacc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profileacc.setObjectName("profileacc")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.profileacc)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_5 = QtWidgets.QWidget(self.profileacc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton = QtWidgets.QPushButton(self.widget_5)
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/whiteIcons/icons/whiteIcons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_15.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label)
        self.verticalLayout_9.addWidget(self.widget_5)
        self.frame_8 = QtWidgets.QFrame(self.profileacc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.myprofile = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.myprofile.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/whiteIcons/icons/whiteIcons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myprofile.setIcon(icon5)
        self.myprofile.setIconSize(QtCore.QSize(20, 20))
        self.myprofile.setAutoDefault(True)
        self.myprofile.setFlat(False)
        self.myprofile.setObjectName("myprofile")
        self.verticalLayout_16.addWidget(self.myprofile)
        self.logout = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.logout.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/whiteIcons/icons/whiteIcons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout.setIcon(icon6)
        self.logout.setIconSize(QtCore.QSize(20, 20))
        self.logout.setAutoDefault(True)
        self.logout.setFlat(False)
        self.logout.setObjectName("logout")
        self.verticalLayout_16.addWidget(self.logout)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.verticalLayout_6.addWidget(self.profileacc, 0, QtCore.Qt.AlignBottom)
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        self.mainBody.setGeometry(QtCore.QRect(231, 0, 781, 601))
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QWidget(self.mainBody)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.headerFrame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBtn = QtWidgets.QPushButton(self.widget)
        self.menuBtn.setText("")
        self.menuBtn.setIcon(icon)
        self.menuBtn.setIconSize(QtCore.QSize(24, 24))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_2.addWidget(self.menuBtn)
        self.appHeadear = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.appHeadear.setFont(font)
        self.appHeadear.setObjectName("appHeadear")
        self.horizontalLayout_2.addWidget(self.appHeadear)
        self.horizontalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.widget_2 = QtWidgets.QWidget(self.headerFrame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchFrame = QtWidgets.QFrame(self.widget_2)
        self.searchFrame.setMinimumSize(QtCore.QSize(140, 0))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.searchFrame)
        self.label_2.setMinimumSize(QtCore.QSize(30, 30))
        self.label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/blueIcons/icons/blueIcons/search.svg"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.search = QtWidgets.QLineEdit(self.searchFrame)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        self.search.setFont(font)
        self.search.setObjectName("search")
        self.horizontalLayout_4.addWidget(self.search)
        self.horizontalLayout_3.addWidget(self.searchFrame, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.headerFrame)
        self.cardsFrame = QtWidgets.QWidget(self.mainBody)
        self.cardsFrame.setObjectName("cardsFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.cardsFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.card1 = QtWidgets.QFrame(self.cardsFrame)
        self.card1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card1.setObjectName("card1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.card1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.card1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.equipmentIcon = QtWidgets.QLabel(self.frame)
        self.equipmentIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.equipmentIcon.setText("")
        self.equipmentIcon.setPixmap(QtGui.QPixmap(":/blueIcons/icons/blueIcons/hard-drive.svg"))
        self.equipmentIcon.setScaledContents(True)
        self.equipmentIcon.setObjectName("equipmentIcon")
        self.verticalLayout_3.addWidget(self.equipmentIcon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.equipment = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.equipment.setFont(font)
        self.equipment.setAlignment(QtCore.Qt.AlignCenter)
        self.equipment.setObjectName("equipment")
        self.verticalLayout_3.addWidget(self.equipment)
        self.equipmentInOut = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.equipmentInOut.setFont(font)
        self.equipmentInOut.setText("")
        self.equipmentInOut.setAlignment(QtCore.Qt.AlignCenter)
        self.equipmentInOut.setObjectName("equipmentInOut")
        self.verticalLayout_3.addWidget(self.equipmentInOut)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_6.addWidget(self.card1)
        self.card2 = QtWidgets.QFrame(self.cardsFrame)
        self.card2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card2.setObjectName("card2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.card2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.card2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.borrowerIcon = QtWidgets.QLabel(self.frame_2)
        self.borrowerIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.borrowerIcon.setText("")
        self.borrowerIcon.setPixmap(QtGui.QPixmap(":/blueIcons/icons/blueIcons/user.svg"))
        self.borrowerIcon.setScaledContents(True)
        self.borrowerIcon.setObjectName("borrowerIcon")
        self.verticalLayout_4.addWidget(self.borrowerIcon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.borrower = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.borrower.setFont(font)
        self.borrower.setAlignment(QtCore.Qt.AlignCenter)
        self.borrower.setObjectName("borrower")
        self.verticalLayout_4.addWidget(self.borrower, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.borrowerInOut = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.borrowerInOut.setFont(font)
        self.borrowerInOut.setText("")
        self.borrowerInOut.setAlignment(QtCore.Qt.AlignCenter)
        self.borrowerInOut.setObjectName("borrowerInOut")
        self.verticalLayout_4.addWidget(self.borrowerInOut)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_6.addWidget(self.card2)
        self.card3 = QtWidgets.QFrame(self.cardsFrame)
        self.card3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card3.setObjectName("card3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.card3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.card3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.timeIcon = QtWidgets.QLabel(self.frame_3)
        self.timeIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.timeIcon.setText("")
        self.timeIcon.setPixmap(QtGui.QPixmap(":/blueIcons/icons/blueIcons/clock.svg"))
        self.timeIcon.setScaledContents(True)
        self.timeIcon.setObjectName("timeIcon")
        self.verticalLayout_8.addWidget(self.timeIcon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.time = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.time.setFont(font)
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.verticalLayout_8.addWidget(self.time, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.timeInOut = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.timeInOut.setFont(font)
        self.timeInOut.setText("")
        self.timeInOut.setAlignment(QtCore.Qt.AlignCenter)
        self.timeInOut.setObjectName("timeInOut")
        self.verticalLayout_8.addWidget(self.timeInOut)
        self.verticalLayout_10.addWidget(self.frame_3)
        self.horizontalLayout_6.addWidget(self.card3)
        self.card4 = QtWidgets.QFrame(self.cardsFrame)
        self.card4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card4.setObjectName("card4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.card4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.card4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.dateIcon = QtWidgets.QLabel(self.frame_4)
        self.dateIcon.setMaximumSize(QtCore.QSize(24, 24))
        self.dateIcon.setText("")
        self.dateIcon.setPixmap(QtGui.QPixmap(":/blueIcons/icons/blueIcons/calendar.svg"))
        self.dateIcon.setScaledContents(True)
        self.dateIcon.setObjectName("dateIcon")
        self.verticalLayout_12.addWidget(self.dateIcon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.date = QtWidgets.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.date.setFont(font)
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")
        self.verticalLayout_12.addWidget(self.date, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.dateInOut = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.dateInOut.setFont(font)
        self.dateInOut.setText("")
        self.dateInOut.setAlignment(QtCore.Qt.AlignCenter)
        self.dateInOut.setObjectName("dateInOut")
        self.verticalLayout_12.addWidget(self.dateInOut)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.horizontalLayout_6.addWidget(self.card4)
        self.verticalLayout.addWidget(self.cardsFrame)
        self.mainFrame = QtWidgets.QWidget(self.mainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.mainFrame)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_5 = QtWidgets.QFrame(self.widget_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listLabel = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(10)
        self.listLabel.setFont(font)
        self.listLabel.setStyleSheet("color:rgb(30, 129, 176)")
        self.listLabel.setScaledContents(False)
        self.listLabel.setObjectName("listLabel")
        self.horizontalLayout_8.addWidget(self.listLabel, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.viewmoreBtn = QtWidgets.QPushButton(self.frame_5)
        self.viewmoreBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        self.viewmoreBtn.setFont(font)
        self.viewmoreBtn.setStyleSheet("color: rgb(30, 129, 176);")
        self.viewmoreBtn.setIconSize(QtCore.QSize(20, 20))
        self.viewmoreBtn.setFlat(True)
        self.viewmoreBtn.setObjectName("viewmoreBtn")
        self.horizontalLayout_8.addWidget(self.viewmoreBtn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_14.addWidget(self.frame_7)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.equip.setText(_translate("MainWindow", "Devices"))
        self.borrower_1.setText(_translate("MainWindow", "Borrower"))
        self.transactlist.setText(_translate("MainWindow", "Transaction List"))
        self.label.setText(_translate("MainWindow", "Admin"))
        self.myprofile.setText(_translate("MainWindow", "My Profile"))
        self.logout.setText(_translate("MainWindow", "Logout"))
        self.appHeadear.setText(_translate("MainWindow", "Dashboard"))
        self.search.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.listLabel.setText(_translate("MainWindow", "Transaction List"))
        self.viewmoreBtn.setText(_translate("MainWindow", "View More"))
#import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
