# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomePage0.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1013, 601)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1021, 601))
        self.widget.setStyleSheet("#widget{\n"
"    background-color:#eeeee4;\n"
"}\n"
"#title{\n"
"    color:#1e81b0;\n"
"}\n"
"#signinButton, #signupButton{\n"
"    border-radius:10px;\n"
"    border:2px solid #1e81b0;\n"
"    color:#1e81b0;\n"
"    background-color:#cbe4e8;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.title = QtWidgets.QLabel(self.widget)
        self.title.setGeometry(QtCore.QRect(220, 140, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setStyleSheet("")
        self.title.setObjectName("title")
        self.signinButton = QtWidgets.QPushButton(self.widget)
        self.signinButton.setGeometry(QtCore.QRect(350, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.signinButton.setFont(font)
        self.signinButton.setStyleSheet("")
        self.signinButton.setObjectName("signinButton")
        self.signupButton = QtWidgets.QPushButton(self.widget)
        self.signupButton.setGeometry(QtCore.QRect(610, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.signupButton.setFont(font)
        self.signupButton.setStyleSheet("")
        self.signupButton.setObjectName("signupButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "MONITORING EQUIPMENT SYSTEM"))
        self.signinButton.setText(_translate("Dialog", "Sign In"))
        self.signupButton.setText(_translate("Dialog", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
